studentRecord.exe: linkedlist.o addLast.o removeLast.o display.o addFirst.o removeFirst.o sorted.o middleNode.o printPrime.o Del_all.o printnth.o printnLast.o check_SLL_CLL.o
	gcc linkedlist.o addLast.o removeLast.o display.o addFirst.o removeFirst.o sorted.o middleNode.o printPrime.o Del_all.o printnth.o printnLast.o check_SLL_CLL.o -o studentRecord.exe
linkedlist.o: linkedlist.c
	gcc -c linkedlist.c -o linkedlist.o
addLast.o: addLast.c
	gcc -c addLast.c -o addLast.o
removeLast.o: removeLast.c
	gcc -c removeLast.c -o removeLast.o
display.o: display.c
	gcc -c display.c -o display.o
addFirst.o: addFirst.c
	gcc -c addFirst.c -o addFirst.o
removeFirst.o: removeFirst.c
	gcc -c removeFirst.c -o removeFirst.o
sorted.o: sorted.c
	gcc -c sorted.c -o sorted.o
middleNode.o: middleNode.c
	gcc -c middleNode.c -o middleNode.o
printPrime.o: printPrime.c
	gcc -c printPrime.c -o printPrime.o
DelAll.o: Del_all.c
	gcc -c Del_all.c -o Del_all.o
printnth.o: printnth.c
	gcc -c printnth.c -o printnth.o
printnLast.o: printnLast.c
	gcc -c printnLast.c -o printnLast.o
check_SLL_CLL.o: check_SLL_CLL.c
	gcc -c check_SLL_CLL.c
