BST.exe: BST_main.o insert.o search.o preorder.o postorder.o inorder.o findmin.o findmax.o Del.o
	gcc BST_main.o insert.o search.o preorder.o postorder.o inorder.o findmin.o findmax.o Del.o -o BST.exe
BST_main.o: BST_main.c
	gcc -c BST_main.c -o BST_main.o	
insert.o: insert.c 
	gcc -c insert.c -o insert.o	
search.o: search.c
	gcc -c search.c -o search.o	
preorder.o: preorder.c
	gcc -c preorder.c -o preorder.o	
postorder.o: postorder.c
	gcc -c postorder.c -o postorder.o	
inorder.o: inorder.c
	gcc -c inorder.c -o inorder.o	
findmin.o: findmin.c
	gcc -c findmin.c -o findmin.o	
findmax.o: findmax.c
	gcc -c findmax.c -o findmax.o
Del.o: Del.c
	gcc -c Del.c -o Del.o
